### PR TITLE
Add support for custom backend.

### PR DESCRIPTION
**Pull request by pbryan**
Did my best to maintain your style conventions. If you'd be willing to forego 2.6 compatibility, could easily make imports programmatic.

### CODE REVIEW

**Comment by wbond** [comment]
I rebased your changes on master and tried to push to your branch but it closed this PR. Weird behavior by GitHub. Anyway, check out https://github.com/wbond/oscrypto/tree/custom-backend and see if that works on your end? Unfortunately GitHub won't let me re-open the PR since it says there are no changes.

We should probably find a way to test it with a Mock custom backend of some sort.

**Comment by pbryan** [comment]
Looks good. In my testing, I simply mocked the _openssl backend as the custom backend package. In my work on PKCS #11, I've copied the _openssl backend, and replaced only the functions that I'm using with the hardware security module.

**Comment by pbryan** [comment]
Alright, let me think more about that. Time permitting, I'm planning on having a full PKCS #11 backend, so it won't be selective. This opens up the door for creating a pure Python backend too.

**Comment by pbryan** [comment]
I just tried your branch, and it seems broken since the introduction of imp to attempt to find modules. As far as I know, find_module can't resolve at the package level. Any chance of reverting that change? Alternative will be I'll keep running on my own branch and try to keep it in lock step with yours.

**Pull request closed without merging**
