### PR TITLE
Fixes #35: Pin libcrypto and libssl dylibs only on Catalina

### LINKED ISSUE #35: oscrypto segfaults on catalina
I've come here after an all-day debugging session. tl;dr I think oscrypto is picking up the wrong SSL backend for catalina (OS X 10.15.1) which causes a crash.

There's some workarounds as documented here: https://forums.developer.apple.com/thread/119429
Though that seems pretty gnarly. 

Specifically I'm finding it failing in _libcrypto_cffi:
```
libcrypto_path = _backend_config().get('libcrypto_path')
if libcrypto_path is None:
    libcrypto_path = find_library('crypto')
if not libcrypto_path:
    raise LibraryNotFoundError('The library libcrypto could not be found')

try:
    vffi = FFI()
    vffi.cdef("const char *SSLeay_version(int type);")
    version_string = vffi.string(vffi.dlopen(libcrypto_path).SSLeay_version(0)).decode('utf-8') #### fails here
except (AttributeError):
    vffi = FFI()
    vffi.cdef("const char *OpenSSL_version(int type);")
    version_string = vffi.string(vffi.dlopen(libcrypto_path).OpenSSL_version(0)).decode('utf-8')
```

I suspect we are just picking a version that makes Catalina extremely upset, and so if we can pick a pinned version that would be better.

I posted something similar here: https://github.com/snowflakedb/snowflake-connector-python/issues/235

### PR DESCRIPTION
**Pull request by worldwise001**
Here's a possible fix to pin the versions at least on Catalina.

### CODE REVIEW

**Comment by wbond** [comment]
To get the Circle CI to pass we'll need to do this since Circle got rid of the 9.2.0 image: https://github.com/wbond/asn1crypto/commit/d43d2b56aa00ce29f4022906e85dd0e6115cf9c8.

**Comment by wbond** [comment]
So right now the libcrypto bindings assume that when we see LibreSSL that we have an OpenSSL 1.0.1 compatible API.

It looks like in LibreSSL 2.7 they started adding OpenSSL 1.0.2 and 1.1.0 APIs. Because of this I think it would be safest if we default to libcrypto.42.dylib and libssl.44.dylib.

Here is the version info I got for libssl on Catalina:

```
libssl.35.dylib:libressl-2.2
libssl.43.dylib:libressl-2.5
libssl.44.dylib:libressl-2.6
libssl.46.dylib:libressl-2.8
```

**Comment by worldwise001** [comment]
Oh interesting. I can change that.

**Comment by worldwise001** [comment]
wow I am usually much better at catching linter problems.

**Comment by wbond** [comment]
Thanks for all of the digging and the fix!

**Pull request merged**
